name: CMake build & run
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake --preset release
    - name: Build
      run: cmake --build --preset release
    - name: Run
      run: build/bin/blkchn
